# SERVER CONFIG

server.port=8080

# POSTGRES DATABASE CONFIG

spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA / HIBERNATE CONFIG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# LOGGING SETTINGS - DEV

logging.level.root=INFO
logging.level.com.example.url_shortener=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n


# APP SETTINGS

app.base-url=http://localhost:8080